{
    "appDir": "./",
    "baseUrl": "./",
    "dir": "./compress",
    "paths": {
        "base": "base/base/base",
        "h5_base" : "base/base/h5_base",
        "handlebars" : "base/handlebars-v2.0.0",
        "hbs" : "base/hbs",
        "text" : "base/text",
        "dialog" : "moudle/ui/dialog/dialog",
        "select" : "moudle/ui/select/select",
        "btn" : "moudle/ui/btn/btn",
        "lazyload" : "moudle/ui/lazyload/lazyload",
        "slide" : "moudle/ui/slidebanner/slidebanner",
        "config" : "moudle/config/config",
        "audio":"moudle/ui/audio/audio",
        "ajax":"moudle/ui/ajax/ajax",
        "city":"moudle/data/city",
        "lang":"moudle/data/lang",
        "common":"moudle/app/common/common",
        "buyplug":"moudle/app/buyplug/buyplug"
    },
    "fileExclusionRegExp": "/.hbs$/",
    "keepBuildDir": true,
    "skipDirOptimize": true,
    "normalizeDirDefines": "skip",
    "optimize": "uglify",
    "modules": []
}
